name:                discrete-event-simulator
version:             0.1.0.0
github:              "turlando/discrete-event-simulator"
license:             AGPL-3
author:              "Tancredi Orlando"
maintainer:          "tancredi.orlando@gmail.com"
copyright:           "2021 Tancredi Orlando"

extra-source-files:
- README.md
- LICENSE.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/turlando/discrete-event-simulator#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- pretty-simple

library:
  source-dirs: src

default-extensions:
- MultiParamTypeClasses
- RankNTypes

executables:
  discrete-event-simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discrete-event-simulator

tests:
  discrete-event-simulator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discrete-event-simulator
